services:
  jellyfin_rd:
    container_name: jellyfin_rd
    image: j0113/jellyfin_rd:latest
    volumes:
      - ./libary:/jellyfin-rd/library                # Mount the libary folder on the docker host.
      - ./settings.json:/jellyfin-rd/settings.json   # Mount the settings file
    ports:
      - "8080:8080"